version: '3'
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
  frontend:
    depends_on:
      - backend
    image: frontend
    container_name: frontend
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "4200:4200"